### ISSUE TITLE
1.10.x alpha 版本的 VPN 权限与 VPN 连接建立存在问题

### ISSUE THREAD

**Issue by Aes64X** [kaaass/ZerotierFix#48]
这里单开一个，最先问题应是由 https://github.com/kaaass/ZerotierFix/issues/46  起

我这里的描述

首先，手机为三桑A53，未ROOT，系统 Android 13
由于之前一直使用Frp（么得办法。。全中转带宽遭不住）
换到ZeroTier手机也是第一次安装这个app，版本 1.0.6_011006_alpha

具体表现，不连接或者说连接开关打开后切换程序或者打开设置，总之是离开程序页面再回来，连接开关会回到关闭状态。
流量检测也看不到这个版本使用过任何流量，无论移动网络，WLAN下，流量使用始终是0KB,也就是这玩意不产生任何连接。
至于app不申请VPN权限，随后安装了上一个版本，产生连接后才会申请VPN权限，这里应是没什么问题
主要问题就是1.0.6_011006_alpha版本没有任何连接动作。

如您有类似问题，欢迎在此继续讨论反馈，这将在问题解决后关闭。

**Comment by kaaass** [comment]
目前看起来是权限相关的问题。1.10.x 确实修改了这一部分，我检查一下

**Comment by liyang8246** [comment]
我也遇到了同样的问题

**Comment by superabbite1** [comment]
我也是 配置了但是没有连接上服务器

**Comment by liujianying** [comment]
E/NetworkListFragment: stopService() returned false
E/EventBus: Could not dispatch event: class net.kaaass.zerotierfix.events.NetworkListCheckedChangeEvent to subscribing class class net.kaaass.zerotierfix.ui.NetworkListFragment
    java.lang.IllegalStateException: Fragment NetworkListFragment{86c197a} (83da3e61-14fb-4769-9952-3b6f9af14396 id=0x7f0800d7) is attempting to registerForActivityResult after being created. Fragments must call registerForActivityResult() before they are created (i.e. initialization, onAttach(), or onCreate()).
        at androidx.fragment.app.Fragment.prepareCallInternal(Fragment.java:3588)
        at androidx.fragment.app.Fragment.registerForActivityResult(Fragment.java:3555)
        at net.kaaass.zerotierfix.ui.NetworkListFragment.sendStartServiceIntent(NetworkListFragment.java:244)
        at net.kaaass.zerotierfix.ui.NetworkListFragment.onNetworkListCheckedChangeEvent(NetworkListFragment.java:665)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
        at org.greenrobot.eventbus.BackgroundPoster.run(BackgroundPoster.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by kaaass** [comment]
@liujianying 感谢提供日志！这块代码确实在 1.10.x 重构了一下，看起来是权限申请存在一些问题

**Comment by Aes64X** [comment]
[ZeroTier-BETA.zip](https://github.com/kaaass/ZerotierFix/files/11767227/ZeroTier-BETA.zip)
来来来，大佬估计太忙了，我这个打包党分担下。
用在线编译搞的，已经打了  https://github.com/kaaass/ZerotierFix/pull/49   补丁
自己测试通过，你们可以下了试试。

**Comment by Aes64X** [comment]
感谢 @sffxzzp 的在线项目，不然就我这破笔记本我是打死也不搞编译环境。

**Comment by sffxzzp** [comment]
> 感谢 @sffxzzp 的在线项目，不然就我这破笔记本我是打死也不搞编译环境。

对 Linux 比较熟悉的话可以用 gitpod.io 来进行一些测试和编译操作，我也是用这个的，免费时间一般来说够用。
另外，现在我似乎搞定了使用 CMake 编译 .so 文件了，已经编译通过，但目前还没测试过编译进 apk 之后能不能正常使用。

**Comment by kaaass** [comment]
1.0.8_011006_alpha 版本包含了可能与此 Issue 相关的另一项修复，请注意更新
