### ISSUE TITLE
上传自定义planet文件时崩溃。

### ISSUE THREAD

**Issue by 2335662257** [kaaass/ZerotierFix#79]
**安卓系统** ：lineageOs
**安卓版本**：7.1.2
**操作步骤**：设置-上传planet文件
**LogCat日志**：
`01-18 14:21:33.769  5599  5599 D AndroidRuntime: Shutting down VM
01-18 14:21:33.770  5599  5599 E AndroidRuntime: FATAL EXCEPTION: main
01-18 14:21:33.770  5599  5599 E AndroidRuntime: Process: net.kaaass.zerotierfix, PID: 5599
01-18 14:21:33.770  5599  5599 E AndroidRuntime: java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadLocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at org.apache.commons.io.IOUtils.<clinit>(IOUtils.java:183)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1043)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:952)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at net.kaaass.zerotierfix.ui.PrefsFragment.lambda$onAttach$0$net-kaaass-zerotierfix-ui-PrefsFragment(PrefsFragment.java:86)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at net.kaaass.zerotierfix.ui.PrefsFragment$$ExternalSyntheticLambda6.onActivityResult(D8$$SyntheticClass)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.Fragment.performStart(Fragment.java:3167)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2902)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:359)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:6701)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.Activity.performRestart(Activity.java:6775)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:6780)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-18 14:21:33.770  5599  5599 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-18 14:21:33.772  1288  2961 W ActivityManager:   Force finishing activity net.kaaass.zerotierfix/.ui.PrefsActivity`

**Comment by 2335662257** [comment]
主要看这个错误：
java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadLocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)
我测试我得华为P40pro（安卓10）是可以成功上传的

**Comment by kaaass** [comment]
感谢报告！看起来似乎是后向兼容的问题，一个依赖库引了 Android 8.0 才引入的一个类，所以之前版本在复制文件时会崩溃。我晚点试着修一下。

**Comment by 2335662257** [comment]
> 感谢报告！看起来似乎是后向兼容的问题，一个依赖库引了 Android 8.0 才引入的一个类，所以之前版本在复制文件时会崩溃。我晚点试着修一下。

感谢大佬回复! 我还有个问题想请教下，这个app里面的“通过ZeroTier路由” 的选项作用是什么呢

**Comment by kaaass** [comment]
“通过 ZeroTier 路由” 会增加一条默认路由，让全部手机流量都走 Zt 网络（前提是后台也要配置 0.0.0.0/0 的路由项）。一般情况下应该用不太到这个功能。

**Comment by 2335662257** [comment]
> “通过 ZeroTier 路由” 会增加一条默认路由，让全部手机流量都走 Zt 网络（前提是后台也要配置 0.0.0.0/0 的路由项）。一般情况下应该用不太到这个功能。

了解了，谢谢

**Comment by kaaass** [comment]
修复啦，方便的话可以用这个包测试下 @2335662257 
[app-debug.apk.zip](https://github.com/kaaass/ZerotierFix/files/14207282/app-debug.apk.zip)
